export const DEFAULT_DARK: Record<string, string> = {
  '--background': '#2A2A2A',
  '--secondary-background': '#2A2A2A',
  '--bg2': '#2E2D33',
  '--bg3': '#35343B',
  '--bg4': '#3C3B42',
  '--bg5': '#43424A',
  '--foreground': '#F0EEE8',
  '--t1': '#F0EEE8',
  '--t2': '#B8B4AA',
  '--t3': '#7A7570',
  '--t4': '#555050',
  '--main': '#D4890A',
  '--main-foreground': '#000000',
  '--border': '#F0EEE8',        // ← borda clara para contraste neobrutalism
  '--b': '#F0EEE8',
  '--b2': '#7A7570',
  '--b3': '#555050',
  '--b-focus': '#FFBF00',
  '--shadow': '4px 4px 0px 0px #F0EEE8',
  '--shadow-nb': '4px 4px 0 #F0EEE8',
  '--shadow-nb-sm': '2px 2px 0 #F0EEE8',
  '--boxShadowX': '4px',
  '--boxShadowY': '4px',
  '--reverseBoxShadowX': '-4px',
  '--reverseBoxShadowY': '-4px',
  '--destructive': '#ef593b',
  '--destructive-foreground': '#ffffff',
  '--c-habit': '#2A2519',
  '--c-habit-b': '#8A7A50',
  '--c-habit-t': '#F5EFDF',
  '--c-habit-bg': '#1e1c16',
  '--c-goal': '#F59E0B',
  '--c-goal-b': '#D97706',
  '--c-goal-t': '#ffffff',
  '--c-goal-bg': '#F59E0B',
  '--c-task': '#6FB8FF',
  '--c-task-b': '#3B82F6',
  '--c-task-t': '#ffffff',
  '--c-task-bg': '#6FB8FF',
  '--c-event': '#9B7BFF',
  '--c-event-b': '#7C5CDB',
  '--c-event-t': '#ffffff',
  '--c-event-bg': '#9B7BFF',
  '--c-note-bg': '#26252B',
  '--c-note-t': '#B8B4AA',
  '--amber': '#F59E0B',
  '--amber-2': '#FBBF24',
  '--amber-deep': '#B45309',
  '--amber-soft': '#FEF3C7',
  '--sun': '#FFD23F',
  '--grass': '#7CE577',
  '--sky': '#6FB8FF',
  '--violet': '#9B7BFF',
  '--coral': '#FF6B6B',
  '--peach': '#FFB39B',
  '--mute': '#7A7570',
  '--mute-2': '#555050',
  '--font-sans': '"Geist", system-ui, sans-serif',
  '--font-mono': '"Geist Mono", monospace',
  '--radius-base': '5px',
  '--radius-sm': '4px',
  '--radius-lg': '8px',
  '--radius-full': '9999px',
  '--spacing': '16px',
  '--border-width': '2px',
  '--shadow-x': '4px',
  '--shadow-y': '4px',
  '--shadow-color': '#F0EEE8',
  '--section-gap': '40px',
  '--grid-gap': '16px',
  '--time-icon-color': '#FFFFFF',
}